### ISSUE TITLE
[1.16] Dissolution Chamber Recipes Missing in JEI

### ISSUE THREAD

**Issue by predundant** [InnovativeOnlineIndustries/Industrial-Foregoing#1242]
I saw the same issue reported and closed around Sept 2021, but I this seems to be happening again.  

**Industrial Foregoing Version:industrial-foregoing-1.16.5-3.2.14.7-16.jar

**Titanium Version: titanium-1.16.5-3.2.8.7-22.jar

JEI Version: jei-1.16.5-7.7.1.145.jar

**Crashlog If Applicable (Upload to pastebin/gist): N/A

**Comment by SirOMGitsYOU** [comment]
Any update on this would be great thanks!

**Comment by DSLM** [comment]
fixed in [industrial-foregoing-1.16.5-3.2.14.7-16.jar](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/3525789) and [jei-1.16.5-7.7.1.152.jar](https://www.curseforge.com/minecraft/mc-mods/jei/files/3681294)

**Comment by Xplodin** [comment]
also missing these in 1.18

**Comment by AmmoniumX** [comment]
Any update on this? Can confirm the problem persists on the latest 1.18 version, and the issue appears to be specifically with the infinite steak from the Project Expansion mod, it is probably a conflict with it and the culinary mycelial generator.
