### ISSUE TITLE
[1.16] Description: Rendering entity ContributorsCatEarsRender

### ISSUE THREAD

**Issue by SatmanAUT** [InnovativeOnlineIndustries/Industrial-Foregoing#866]
ATM6 single and multiplayer
as soon i am entering my player inventory game crashes.
I used to be a patrean of Buuz135 on Patreon and got those cat ears. is there any chance that that is the problem. i never checked if i still had them but the crash report is mentioning it. i think its connected to halloween minecraft event. Please help me i want to play minecraft.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/1/20 10:16 AM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:235) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.func_228804_a_(BlockModelRenderer.java:227) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.buuz135.industrial.proxy.client.render.ContributorsCatEarsRender.render(ContributorsCatEarsRender.java:73) ~[?:3.1.1] {re:classloading}
	at com.buuz135.industrial.proxy.client.render.ContributorsCatEarsRender.func_225628_a_(ContributorsCatEarsRender.java:47) ~[?:3.1.1] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:125) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches PlayerRenderer Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches PlayerRenderer Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:EntityRendererManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$23117/893775994.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1417) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230450_a_(SourceFile:111) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230430_a_(SourceFile:92) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:281) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1982072255.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:235) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.func_228804_a_(BlockModelRenderer.java:227) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.buuz135.industrial.proxy.client.render.ContributorsCatEarsRender.render(ContributorsCatEarsRender.java:73) ~[?:3.1.1] {re:classloading}
	at com.buuz135.industrial.proxy.client.render.ContributorsCatEarsRender.func_225628_a_(ContributorsCatEarsRender.java:47) ~[?:3.1.1] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:125) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches PlayerRenderer Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches PlayerRenderer Transformer,pl:runtimedistcleaner:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 827297
	Entity Name: TheSatman
	Entity's Exact location: 2261.93, 85.00, 401.56
	Entity's Block location: World: (2261,85,401), Chunk: (at 5,5,1 in 141,25; contains blocks 2256,0,400 to 2271,255,415), Region: (4,0; contains chunks 128,0 to 159,31, blocks 2048,0,0 to 2559,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.PlayerRenderer@3b521a46
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:EntityRendererManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$23117/893775994.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1417) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230450_a_(SourceFile:111) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230430_a_(SourceFile:92) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:281) ~[?:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.InventoryScreen
	Mouse location: Scaled: (320, 180). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['TheSatman'/827297, l='ClientLevel', x=2261.93, y=85.00, z=401.56]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 32249173 game time, 37483261 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:600) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1982072255.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1150366272 bytes (1097 MB) / 6385303552 bytes (6089 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.25.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.25
	FML Language Providers: 
		javafml@34.1
		minecraft@1
		kotori_scala@2.13.3-build-3
	Mod List: 
		AdditionalEnchantedMiner-1.16.3-16.1.1.jar QuarryPlus {quarryplus@16.1.1 DONE}
		simplemagnets-1.0.8-mc1.16.3.jar Simple Magnets {simplemagnets@1.0.8 DONE}
		missingstructurefix-1.0.jar Missing Structure Fix {missingstructurefix@1.0 DONE}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		modnametooltip_1.16.2-1.15.0.jar Mod Name Tooltip {modnametooltip@1.15.0 DONE}
		IronJetpacks-1.16.3-4.1.2.jar Iron Jetpacks {ironjetpacks@4.1.2 DONE}
		ReAuth-1.16-Forge-3.9.2.jar ReAuth {reauth@3.9.2 DONE}
		Powah-1.16.3-2.3.3.jar Powah {powah@2.3.3 DONE}
		rangedpumps-0.8.2.jar Ranged Pumps {rangedpumps@0.8.2 DONE}
		jumbofurnace-1.16.3-2.1.0.0.jar Jumbo Furnace {jumbofurnace@1.16.3-2.1.0.0 DONE}
		Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar Wither Skeleton Tweaks {wstweaks@5.2.1 DONE}
		reliquary-1.16.3-1.3.4.1039.jar Reliquary {xreliquary@1.16.3-1.3.4.1039 DONE}
		randompatches-1.16.2-1.22.1.2.jar RandomPatches {randompatches@1.16.2-1.22.1.2 DONE}
		Morpheus-1.16.3-4.2.59.jar Morpheus {morpheus@version DONE}
		WaterStrainer-1.16.3-10.0.0.jar Water Strainer {waterstrainer@1.16.3-10.0.0 DONE}
		JustEnoughResources-1.16.3-0.12.0.102.jar Just Enough Resources {jeresources@0.12.0.102 DONE}
		confdespawntimer_1.16.3_1.3.jar Configurable Despawn Timer {confdespawntimer@1.3 DONE}
		shetiphiancore-1.16-3.8.4.jar ShetiPhian-Core {shetiphiancore@3.8.4 DONE}
		MysticalAgradditions-1.16.3-4.1.0.jar Mystical Agradditions {mysticalagradditions@4.1.0 DONE}
		emojiful-1.16.3-2.1.0.jar Emojiful {emojiful@1.16.3-2.1.0 DONE}
		refinedstorage-1.9.8.jar Refined Storage {refinedstorage@1.9.8 DONE}
		corpse-1.16.3-1.1.8.jar Corpse {corpse@1.16.3-1.1.8 DONE}
		PackMenu-1.16.3-2.3.0.jar Pack Menu {packmenu@2.3.0 DONE}
		alltheores-0.1.13-1.16.3-34.1.0.jar AllTheOres {alltheores@0.1.13 DONE}
		industrial-foregoing-1.16.3-3.1.1-a834e76.jar Industrial Foregoing {industrialforegoing@3.1.1 DONE}
		cleancut-mc1.16-2.2-forge.jar Clean Cut {cleancut@2.2 DONE}
		torchmaster-2.3.4-alpha.jar Torchmaster {torchmaster@2.3.4-alpha DONE}
		repurposed_structures-1.16.3-2.2.11.jar Repurposed Structures {repurposed_structures@1.16.3-2.2.11 DONE}
		BiomesOPlenty-1.16.3-12.0.0.412-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.410 DONE}
		SilentGear-1.16.3-2.3.2+167.jar Silent Gear {silentgear@2.3.2+167 DONE}
		portality-1.16.3-3.1.1.jar Portality {portality@3.1.1 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Botania-1.16.3-409.jar Botania {botania@1.16.3-409 DONE}
		tanknull-2.1-1.16.2.jar Tank Null {tanknull@2.1-1.16.2 DONE}
		angelring-1.16.3-1.3.3.jar Angel Ring {angelring@1.3.3 DONE}
		ExtraStorage-1.16.3-1.1.1.jar Extra Storage {extrastorage@1.1.1 DONE}
		NaturesAura-32.0.jar Nature's Aura {naturesaura@32.0 DONE}
		constructionwand-1.16.2-1.5.jar Construction Wand {constructionwand@1.16.2-1.5 DONE}
		mcws-roofs-1.16.3-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		globalxp-1.16.3-v1.4.15.jar Global XP {globalxp@v1.4.15 DONE}
		cloth-config-forge-4.1.0.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		FastLeafDecay-v25.jar FastLeafDecay {fastleafdecay@v25 DONE}
		BetterMineshaftsForge-1.16.2-1.0.1.jar YUNG's Better Mineshafts {bettermineshafts@1.16.2-1.0.1 DONE}
		ClientTweaks_1.16.3-5.2.0.jar Client Tweaks {clienttweaks@5.2.0 DONE}
		nomowanderer_MC1.16.3_1.0.jar NoMoWanderer {nomowanderer@1.16.3_1.0 DONE}
		doubledoors_1.16.3_2.1.jar Double Doors {doubledoors@2.1 DONE}
		mining-helmet-1.16.3-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		woot-1.16.3-1.0.0.0.jar Woot {woot@1.16.3-1.0.0.0 DONE}
		bagofyurting-1.16.3-1.1.0.1.jar Bag of Yurting {bagofyurting@1.1.0.1 DONE}
		jei-1.16.3-7.6.0.49.jar Just Enough Items {jei@7.5.0.43 DONE}
		AttributeFix-1.16.3-8.0.2.jar AttributeFix {attributefix@8.0.2 DONE}
		Mekanism-1.16.3-10.0.15.441.jar Mekanism {mekanism@10.0.15 DONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 DONE}
		shutupexperimentalsettings-1.0.1.jar Shutup Experimental Settings! {shutupexperimentalsettings@1.0.1 DONE}
		light-overlay-5.5.4.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		NaturesCompass-1.16.3-1.8.5.jar Nature's Compass {naturescompass@1.16.3-1.8.5 DONE}
		LibX-1.16.3-1.0.2.jar LibX {libx@1.16.3-1.0.2 DONE}
		phosphophyllite-1.16.3-0.0.5-beta.jar Phosphophyllite {phosphophyllite@0.0.5 DONE}
		engineerstools-1.16.3-1.1.1-b1.jar Engineer's Tools {engineerstools@1.1.1-b1 DONE}
		FarmingForBlockheads_1.16.3-7.2.0.jar Farming for Blockheads {farmingforblockheads@7.2.0 DONE}
		pneumaticcraft-repressurized-1.16.3-2.4.5-62.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.3-2.4.5-62 DONE}
		pedestals-0.8b.jar Pedestals {pedestals@0.8b DONE}
		extradisks-1.16.3-1.3.3.jar Extra Disks {extradisks@1.3.3 DONE}
		ironchest-1.16.3-11.2.6.jar Iron Chests {ironchest@1.16.3-11.2.6 DONE}
		MythicBotany-1.16.3-1.1.3.jar MythicBotany {mythicbotany@1.16.3-1.1.3 DONE}
		forge-1.16.3-34.1.25-client.jar Minecraft {minecraft@1.16.3 DONE}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta DONE}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ImmersiveEngineering-1.16.3-4.1.0-124.jar Immersive Engineering {immersiveengineering@1.16.3-4.1.0-124 DONE}
		useful_railroads-1.16.3-1.4.5.32.jar Useful Railroads {usefulrailroads@1.4.5.32 DONE}
		pamhc2crops-1.16.3-1.0.1.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		allthemodium-1.1.15-1.16.3-34.1.0.jar Allthemodium {allthemodium@1.1.15 DONE}
		Ding-1.16.3-1.2.0.jar Ding {ding@1.2.0 DONE}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 DONE}
		pamhc2foodcore-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 DONE}
		AutoRegLib-1.6-46.jar AutoRegLib {autoreglib@1.6-46 DONE}
		PickleTweaks-1.16.3-5.1.2.jar Pickle Tweaks {pickletweaks@5.1.2 DONE}
		FastFurnace-1.16.3-4.3.0.jar FastFurnace {fastfurnace@4.3.0 DONE}
		allthetweaks-1.1.7-1.16.3-34.1.10.jar All The Tweaks {allthetweaks@1.1.7 DONE}
		kubejs-1603.2.8.73.jar KubeJS {kubejs@1603.2.8.73 DONE}
		byg-1.0.8.jar Oh The Biomes You'll Go {byg@1.0.8 DONE}
		extremeSoundMuffler-2.1.3_Forge-1.16.3.jar Extreme Sound Muffler {extremesoundmuffler@2.1.3_forge-1.16.3 DONE}
		CosmeticArmorReworked-1.16.3-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.3-v1 DONE}
		morered-1.16.3-2.0.0.0.jar More Red {morered@2.0.0.0 DONE}
		xptome-1.16.2-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
		DefaultOptions_1.16.3-12.2.0.jar Default Options {defaultoptions@12.2.0 DONE}
		NetherPortalFix_1.16.3-7.2.0.jar NetherPortalFix {netherportalfix@7.2.0 DONE}
		aiotbotania-1.16.2-1.3.2.jar AIOT Botania {aiotbotania@1.3.2 DONE}
		forge-1.16.3-geckolib-2.1.2.jar GeckoLib {geckolib@2.1.2 DONE}
		ars_nouveau-1.16.3-1.2.4.jar Ars Nouveau {ars_nouveau@1.2.4 DONE}
		managear-1.16.3-2.1.2.jar Mana Gear {managear@1.16.1-2.1.2 DONE}
		KleeSlabs_1.16.3-9.2.0.jar KleeSlabs {kleeslabs@9.2.0 DONE}
		rsgauges-1.16.3-1.2.5-b1.jar Gauges and Switches {rsgauges@1.2.5-b1 DONE}
		CookingForBlockheads_1.16.3-9.2.1.jar Cooking for Blockheads {cookingforblockheads@9.2.1 DONE}
		Controlling-7.0.0.8.jar Controlling {controlling@7.0.0.8 DONE}
		Placebo-1.16.3-4.3.3.jar Placebo {placebo@4.3.3 DONE}
		dankstorage-3.11.jar Dank Storage {dankstorage@3.11 DONE}
		citadel-1.4.1.jar Citadel {citadel@1.4.1 DONE}
		iceandfire-2.1.0-1.16.3.jar Ice and Fire {iceandfire@2.0.3-1.16.3 DONE}
		rats-7.0.0-1.16.3.jar Rats {rats@7.0.0 DONE}
		ratlantis-1.0.0-1.16.3.jar Rats: Ratlantis {ratlantis@1.0.0-1.16.3 DONE}
		ftb-gui-library-1603.1.1.25.jar FTB GUI Library {ftbguilibrary@1603.1.1.25 DONE}
		potionsmaster-0.1.23-1.16.3-34.1.0.jar Potions Master {potionsmaster@0.1.23 DONE}
		culinaryconstruct-forge-1.16.3-4.0.0.1.jar Culinary Construct {culinaryconstruct@1.16.3-4.0.0.1 DONE}
		Bookshelf-1.16.3-8.7.20.jar Bookshelf {bookshelf@8.7.20 DONE}
		BotanyPots-1.16.3-5.1.11.jar BotanyPots {botanypots@5.1.11 DONE}
		u_team_core-1.16.3-3.1.10.183.jar U Team Core {uteamcore@3.1.10.183 DONE}
		buildinggadgets-3.7.1.jar Building Gadgets {buildinggadgets@3.7.1 DONE}
		forge-1.16.3-34.1.25-universal.jar Forge {forge@34.1.25 DONE}
		Psi 1.16-87.jar Psi {psi@1.16-87 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		Aquaculture-1.16.3-2.1.4.jar Aquaculture 2 {aquaculture@1.16.3-2.1.4 DONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		LightingWand-1.16.2-1.7.0.jar Lighting Wand {lightingwand@1.7.0 DONE}
		MekanismGenerators-1.16.3-10.0.15.441.jar Mekanism: Generators {mekanismgenerators@10.0.15 DONE}
		Ma-Essentials-1.16.3-3.4.0.jar Ma Essentials {maessentials@1.16.3-3.4.0 DONE}
		XNetGases-1.16.3-2.0.0.jar XNet Gases {xnetgases@2.0.0 DONE}
		ftb-teams-1.0.1.12.jar FTB Teams {ftbteams@1.0.1.12 DONE}
		absentbydesign-1.16.3-1.1.1.jar Absent By Design Mod {absentbydesign@1.16.3-1.1.1 DONE}
		mcw-bridges-1.0.4-mc1.16.3.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.16.3-1.11.6.83.jar Useful Backpacks {usefulbackpacks@1.11.6.83 DONE}
		resourcefulbees-1.16.3-0.5.5b.jar Resourceful Bees {resourcefulbees@1.16.3-0.5.5b DONE}
		entangled-1.2.7-mc1.16.3.jar Entangled {entangled@1.2.7 DONE}
		endertanks-1.16-1.9.3.jar EnderTanks {endertanks@1.9.3 DONE}
		crashutilities-3.5.jar Crash Utilities {crashutilities@3.5 DONE}
		Compressium-1.16.3-1.1.33.jar Compressium {compressium@1.1.33 DONE}
		MekanismAdditions-1.16.3-10.0.15.441.jar Mekanism: Additions {mekanismadditions@10.0.15 DONE}
		valkyrielib-1.16.3-3.0.3.2.jar ValkyrieLib {valkyrielib@1.16.3-3.0.3.2 DONE}
		Lollipop-1.16.3-3.2.2.jar Lollipop {lollipop@3.2.2 DONE}
		ftb-ranks-1.0.0.7.jar FTB Ranks {ftbranks@1.0.0.7 DONE}
		simplylight-1.16.3-1.0.2.jar Simply Light {simplylight@1.16.3-1.0.2 DONE}
		tgcropesmod-1.16.2-1.1.0.jar Ropes Mod {tgcropesmod@1.16.2-1.1.0 DONE}
		atmadditions-1.16.2-1.0.0.jar All The Mods: Additions {atmadditions@1.16.2-1.0.0 DONE}
		SolarFluxReborn-1.16.3-16.2.3.jar Solar Flux Reborn {solarflux@16.2.3 DONE}
		Patchouli-1.16.2-47.jar Patchouli {patchouli@1.16.2-47 DONE}
		collective-1.16.3-1.53.jar Collective {collective@1.53 DONE}
		camera-1.16.3-1.0.4.jar Camera Mod {camera@1.16.3-1.0.4 DONE}
		MysticalCustomization-1.16.3-2.1.0.jar Mystical Customization {mysticalcustomization@2.1.0 DONE}
		elevatorid-1.16.3-1.7.6.jar Elevator Mod {elevatorid@1.16.3-1.7.6 DONE}
		ftb-ultimine-1603.1.1.12.jar FTB Ultimine {ftbultimine@1603.1.1.12 DONE}
		Runelic-1.16.3-5.0.1.jar Runelic {runelic@5.0.1 DONE}
		DarkUtilities-1.16.3-6.0.3.jar Dark Utilities {darkutils@6.0.3 DONE}
		MekanismTools-1.16.3-10.0.15.441.jar Mekanism: Tools {mekanismtools@10.0.15 DONE}
		cc-tweaked-1.16.3-1.93.1.jar CC: Tweaked {computercraft@1.93.1 DONE}
		trashcans-1.0.3-mc1.16.3.jar Trash Cans {trashcans@1.0.3 DONE}
		TrampleStopper-2.4.3.jar Trample Stopper {tramplestopper@2.4.3 DONE}
		bwncr-1.16.3-3.8.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.3-3.8.15 DONE}
		Cyclic-1.16.3-0.8.3.jar Cyclic {cyclic@1.16.3-0.8.3 DONE}
		BetterAdvancements-1.16.3-0.1.0.102.jar Better Advancements {betteradvancements@0.1.0.102 DONE}
		biggerreactors-1.16.3-0.2.0-beta.jar Bigger Reactors {biggerreactors@0.2.0 DONE}
		Cucumber-1.16.3-4.1.2.jar Cucumber Library {cucumber@4.1.2 DONE}
		TrashSlot_1.16.3-12.2.0.jar TrashSlot {trashslot@12.2.0 DONE}
		flatbedrock-1.16.3-1.1.3.jar Flat Bedrock {flatbedrock@1.16.3-1.1.3 DONE}
		item-filters-2.2.2.18.jar Item Filters {itemfilters@2.2.2.18 DONE}
		elementalcraft-1.16.3-2.3.14.jar ElementalCraft {elementalcraft@1.16.3-2.3.14 DONE}
		platforms-1.16-1.7.6.jar Platforms {platforms@1.7.6 DONE}
		metalbarrels-3.3a.jar Metal Barrels {metalbarrels@3.3a DONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 DONE}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 DONE}
		enviromats-1.16.3-2.0.3.2.jar Environmental Materials {enviromats@1.16.3-2.0.3.2 DONE}
		comforts-forge-1.16.3-4.0.0.1.jar Comforts {comforts@1.16.3-4.0.0.1 DONE}
		appliedenergistics2-8.1.0-beta.2.jar Applied Energistics 2 {appliedenergistics2@8.1.0-beta.2 DONE}
		DimStorage-1.16.3-4.2.1.jar DimStorage {dimstorage@4.2.1 DONE}
		BadMobs-1.16.3-7.0.1.jar BadMobs {badmobs@7.0.1 DONE}
		demagnetize-forge-1.16.2-1.2.2.jar Demagnetize {demagnetize@1.16.2-1.2.2 DONE}
		mcjtylib-1.16-5.0.11.jar McJtyLib {mcjtylib@1.16-5.0.11 DONE}
		rftoolsbase-1.16-2.0.6.jar RFToolsBase {rftoolsbase@1.16-2.0.6 DONE}
		xnet-1.16-3.0.7.jar XNet {xnet@1.16-3.0.7 DONE}
		rftoolspower-1.16-3.0.8.jar RFToolsPower {rftoolspower@1.16-3.0.8 DONE}
		rftoolsbuilder-1.16-3.0.8.jar RFToolsBuilder {rftoolsbuilder@1.16-3.0.8 DONE}
		rftoolsstorage-1.16-2.0.5.jar RFToolsStorage {rftoolsstorage@1.16-2.0.5 DONE}
		rftoolscontrol-1.16-4.0.5.jar RFToolsControl {rftoolscontrol@1.16-4.0.5 DONE}
		restrictions-1.16-3.0.3.jar Restrictions {restrictions@1.16-3.0.3 DONE}
		mahoutsukai-1.16.3-v1.25.1.jar Mahou Tsukai {mahoutsukai@1.16.3-v1.25.1 DONE}
		Toast-Control-1.16.3-4.3.0.jar Toast Control {toastcontrol@4.3.0 DONE}
		mininggadgets-1.6.0.jar Mining Gadgets {mininggadgets@1.6.0 DONE}
		ftb-chunks-1603.1.2.40.jar FTB Chunks {ftbchunks@1603.1.2.40 DONE}
		scuba-gear-1.16.3-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		MysticalAgriculture-1.16.3-4.1.1.jar Mystical Agriculture {mysticalagriculture@4.1.1 DONE}
		CraftingTweaks_1.16.3-12.2.0.jar Crafting Tweaks {craftingtweaks@12.2.0 DONE}
		rftoolsutility-1.16-3.0.11.jar RFToolsUtility {rftoolsutility@1.16-3.0.11 DONE}
		EnchantmentDescriptions-1.16.3-5.0.6.jar EnchantmentDescriptions {enchdesc@5.0.6 DONE}
		ToolBelt-1.16.3-1.15.2.jar Tool Belt {toolbelt@1.15.2 DONE}
		titanium-1.16.3-3.1.0.jar Titanium {titanium@3.1.0 DONE}
		SilentLib-1.16.3-4.8.1+61.jar Silent Lib {silentlib@4.8.1+61 DONE}
		forbidden_arcanus-1.16.3-1.0.2.jar Forbidden & Arcanus {forbidden_arcanus@1.16.3-1.0.2 DONE}
		Quark-r2.4-271.jar Quark {quark@r2.4-271 DONE}
		Apotheosis-1.16.3-4.4.0.jar Apotheosis {apotheosis@4.4.0 DONE}
		JAOPCA-1.16.3-3.4.0.0.jar JAOPCA {jaopca@3.4.0.0 DONE}
		FastWorkbench-1.16.3-4.4.0.jar FastWorkbench {fastbench@4.4.0 DONE}
		StorageDrawers-1.16.3-8.2.1.jar Storage Drawers {storagedrawers@8.2.1 DONE}
		FluxNetworks-1.16.3-6.0.1.4.jar Flux Networks {fluxnetworks@1.16.3-6.0.1.4 DONE}
		enderchests-1.16-1.7.4.jar EnderChests {enderchests@1.7.4 DONE}
		engineersdecor-1.16.3-1.1.3-b2.jar Engineer's Decor {engineersdecor@1.1.3-b2 DONE}
		solcarrot-1.16.3-1.9.8.jar Spice of Life: Carrot Edition {solcarrot@1.16.3-1.9.8 DONE}
		modular-routers-1.16.3-7.1.1-37.jar Modular Routers {modularrouters@1.16.3-7.1.1-37 DONE}
		refinedstorageaddons-0.7.2.jar Refined Storage Addons {refinedstorageaddons@0.7.2 DONE}
		chiselsandbits-0.2.2-ALPHA.jar Chisels & bits {chiselsandbits@NONE DONE}
		balancedenchanting-1.0.jar Balanced Enchanting {balancedenchanting@1.0 DONE}
	Crash Report UUID: cb73ace1-45a7-453c-8de0-8bd1d37a488f
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Launched Version: forge-34.1.25
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.55, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, kubejs:resource_pack (incompatible), packmenu (incompatible), resourcefulbees
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz

**Comment by SatmanAUT** [comment]
i tested it on other mods with industrial foregoing and and without.its 100% the patreon Cat ears.it startet for me at midnight MEZ.so its connected with the halloween

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/e4be2cec5a360796cce9f33615e5da16d8a62c29

**Comment by NillerMedDild** [comment]
This bug still exists in the new version `industrial-foregoing-1.16.4-3.2.0-131d31a`
Crash: https://gist.github.com/NillerMedDild/f71e06d8b2e398cac76754ee7f54f2b6
